###
//get all currencies
GET http://45.14.246.228:8080/CurrencyExchange/currencies

###
//get one currency
GET http://45.14.246.228:8080/CurrencyExchange/currency/CHF

###
//save currency in db and return result
POST http://45.14.246.228:8080/CurrencyExchange/currencies
Content-Type: application/x-www-form-urlencoded

//change code for check,because he can already exist
name = vitalik&
sign = ll&
code = llK


###
//get all ExchangeRates
GET http://45.14.246.228:8080/CurrencyExchange/exchangeRates

###
//get one ExchangeRates by codes name
GET http://45.14.246.228:8080/CurrencyExchange/USDsss

###
//add Exchange rate
POST http://45.14.246.228:8080/CurrencyExchange/exchangeRates
Content-Type: application/x-www-form-urlencoded

//change code for check
baseCurrencyCode = KMO&
targetCurrencyCode = sss&
rate = 0.99

###
//update method
POST http://45.14.246.228:8080/CurrencyExchange/exchangeRate/KMOsss
Content-Type: application/x-www-form-urlencoded

//indicate data
rate = 0.67

###
//get exchange rate
GET http://45.14.246.228:8080/CurrencyExchange/exchange?from=sss&to=USD&amount=15





















