//get all currencies
http://localhost:8080/currencies

//add currencies(you need postman for test this method becouse this method are POST with data x-www-form-urlencoded,three parametrs (name,sign,code))
http://localhost:8080/currencies
